
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    password:
    username:

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false

logging.level:
  org.hibernate.SQL: debug
